### ISSUE TITLE
AIKIDS ADD Button

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#16]
As a **parent or a child** I can **click on an add button** so that **I can write my to do task to the list.**

# Acceptance Criteria: 

* This should be a big addition button
* The button should display a message that tells the child or parent to click it to add an item.
* The button should be located on the left hand side of the screen.
* After clicking the button you are taken to a separate page asking you to insert the name of the item and to also mark it as done or not.

# Tasks: 

- [ ] Download a button with an addition sign and style it so it is big and kept at the left and side of the page with CSS and HTML.
- [ ] Check if the field created on the first attempt of the model to track the task name is still maintained , otherwise create it. 
- [ ] Check if the field created on the first attempt of the modelt to track the done status if still maintained, otherwise create it. 
- [ ] Create or Update the Controller function views.py
- [ ] Create or Update the template for adding item, add_item.html
- [ ] Update the unit test scripts.
- [ ] Test the functionality.
