### ISSUE TITLE
AIKIDS VIEW my tasks

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#19]
As a **child or parent** I can **click a button** so that **I see the list of my tasks on a home page**

# Acceptance Criteria: 

* Table should be displayed 
* Table should be at the centre of the screen listing items to be done.
* When the table is empty it shold let the user know and prompt the user to add an item.
* The user see her progress
* The user should see reminders when about to miss a task.

# Tasks: 

- [ ] Update the view with Bootstrap CSS and HTML.
- [ ] Update the model to print number of items acheived
- [ ] Update the controller function  to include modals to display remiders.
- [ ] Update unit test scritps 
- [ ] test the functionality
