### ISSUE TITLE
AIKIDS to do time management

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#20]
As a **parent or child** I can **see pop up ** so that **to remind me that I have half an hour before the task miss deadline**

# Acceptance Criteria: 

* This should be a pop up.
* The pop up should contain message that half an hour is left before cutt off.
* The pop up should appear at the right hand side of the screan and should be big and colour full.
* After closing this will remove it of the screen.

# Tasks:  
- [ ] Inherit Bootstrap CSS and HTML  to possition the pop up to the right and make it bigger and colourful.
- [ ] Create or update the model function to include the timer.
- [ ] Update the controller function  to include the timer.
- [ ] Update unit test scritps 
- [ ] test the functionality
