### ISSUE TITLE
AIKIDS WORKLOAD management

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#21]
As a **child or parent** I can **how much tasks in total  are done** so that **I improve the speed or relax at performing these tasks**

# Acceptance Criteria: 

* The option should an upward pointing arrow.
* The arrow should display total of items that have been marked as done.
* The option should appear at the top right of the screen.
* After marking an item as done the number increases but if you click toggle or un check the item the number will reduce.

# Tasks: 

- [ ] Download the arrow and use HTML and CSS to style  and position it at the top right.
- [ ] Create or update new field in the model to sum and keep count of the checked as done items. 
- [ ] Update the controller function  
- [ ] Update unit test scritps 
- [ ] test the functionality
