### ISSUE TITLE
AIKIDS CUTTOFF times

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#22]
As a **child for parent ** I can **input an hour and minutes** so that **set time by when the task should be finished.**

# Acceptance Criteria: 

* The option should be dropdown to select hours minutes and seconds.
* The option to be a column on the table next to the respective task.
* The option should be able to redirect me to home where I am able to view the tasks including the resent one with time column.

# Tasks: 

- [ ] Update the view with HTML, CSS and the JS to link the time to the alerts.
- [ ] Create a new field in the model to set and track the time.
- [ ] Update the controller function  
- [ ] Update unit test scritps 
- [ ] test the functionality
