### ISSUE TITLE
AIKIDS Prioritisation

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#23]
As a **child or parent** I can **mark  an item as urgent** so that **I can distinguish and do it first.**

# Acceptance Criteria: 

* The option should be an Exclamaition mark button.
*  When item is mark urgent it will have this exclamation mark as one of the last items of the table.
* The option should not be visible if item is not marked as urgent.
* After marking the item as urgent you should be able to see all items including both urgent and not urgent (unmarked) as a list

# Tasks: 

- [ ] Down load the exclamation mark Icon and use HTML, CSS and JS to put it in your view.
- [ ] Create a new field in the model to track the urgent status. 
- [ ] Update the controller function  
- [ ] Update unit test scritps 
- [ ] test the functionality
