### ISSUE TITLE
AIKIDS CATEGORIZATION

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#24]
As a **child or parent** I can **drop down to category** so that **I can select the desired category at that time**

# Acceptance Criteria: 

* The option should be drop down
* The options should be : 
          1. ARTofAIseeing
          2. MOVIEofAIhearing
          3. GAMEtoBitAI
* The option should appear next to the task name.
* After selecting categories a list containing items from only the three categories shoul show.

# Tasks: 

- [ ] Update the view of HTML and CSS to include a column for category name.
- [ ] Create a new field in the model to track the category name. 
- [ ] Update the controller function  
- [ ] Update unit test scritps 
- [ ] test the functionality
