### ISSUE TITLE
AIKIDS AUTHORISATION

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#25]
As a **child or parent** I can **log into my own profile** so that **so i can nonly see only my tasks**

# Acceptance Criteria: 

* The option should be log in navigation
* The log in button should be in lin with the home button
* The option should appear when not logged in.
* After submitting I should be able to see only my work.

# Tasks: 

- [ ] Update the view: the poll design HTML and CSS  for the navigation bar to include log in.
- [ ] Create a supper user.
- [ ] Update the controller function  
- [ ] Update unit test scritps 
- [ ] test the functionality
