### ISSUE TITLE
AIKIDS ADMIN View

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#26]
As a **tutor or administrator** I can **click a button ** so that *I see the list of my tasks on a home page*

# Acceptance Criteria: 

* Table should be displayed
* Table should be at the centre of the screen listing items to be done.
* The user see her progress
* The user should see reminders when about to miss a task.

# Tasks: 

- [ ] Update the view with Bootstrap CSS and HTML.
- [ ] Update the model to print number of items acheived
- [ ]Update the controller function to include modals to display remiders.
- [ ] Update unit test scritps 
- [ ] test the functionality
