### ISSUE TITLE
AIKIDS ADMIN Edit

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#27]
As a * as parent or child * I can *click on an edit button* so that *I can reword my task*

# Acceptance Criteria: 

* This should be a big addition button
* The button should read Edit 
* The option should appear next to the delete button and be the part of the table.
* The child or parent must be directed to a separate page displaying the original item but with editable format.
* After clicking update, they should be redirected to the home page where they see the ariginal list inclusive of the recently updated item.

# Tasks: 

- [ ] Inherit the button styling from Bootstrap CSS  and employ table from HTML.
- [ ] Update the controller function  to reflect the update button and anable users to edit and submit the updated information.
- [ ] Adjust the template and view such that they are redirected to the home page.
- [ ] Update unit test scritps 
- [ ] test the functionality
