### ISSUE TITLE
AIKIDS ADMIN Delete

### ISSUE THREAD

**Issue by sibekov** [sibekov/aikidsclub#28]
As a *tutor or administrator* I can **click delete** so that **the unwanted item can be removed from my list**

# Acceptance Criteria: 

* This option should be a button  with place holder name of delete.
* The button should display a message that tells the child or parent to click it to delete an item, on hover.
* The option should appear as last column of a table.
* After submiting I should be able to see the rest of the items with the exception on just deleted.

# Tasks: 

- [ ] Inherit Bootstrap  CSS button  with the styles and bright colours; 
- [ ] Update the HTML to desplay this button as the last item of the table.
- [ ] Update the controller function  and add defensive design to check if the user really would like to delete the item.  Update the 
function so that they are redirected to the home page.
- [ ] Update unit test scritps 
- [ ] test the functionality
